### ISSUE TITLE
set_all(stack, 1) only sets the first relay on

### ISSUE THREAD

**Issue by audstanley** [SequentMicrosystems/4relay-rpi#2]
This works just fine, all relays on, then all relays off.
```python
lib4relay.set(0, 1, 1)
lib4relay.set(0, 2, 1)
lib4relay.set(0, 3, 1)
lib4relay.set(0, 4, 1)
lib4relay.set_all(0, 0)
```

This, however, only turns on the first relay in stack 0. (the second line works fine.)
```python
lib4relay.set_all(0, 1) # only turns on first relay
lib4relay.set_all(0, 0)

```

**Comment by alexburcea2877** [comment]
Hi Richard,

The "set_all(stack, value)" function set the value on bits for all relays.
If you want to enable all relays set the value to 15 (or 0x0f or
0b00001111)
The function is useful for turn various relays on or off in a single command
If you want to turn relay 2 and 3 on and the rest off, issue command "
lib4relay.set_all(0, 0b0110)"

Regards,
Alex.

În joi, 25 iun. 2020 la 23:19, Richard Stanley <notifications@github.com> a
scris:

**Comment by audstanley** [comment]
OH that make sense. thank you.
awesome.
