### ISSUE TITLE
relay8 id 0 not detected

### ISSUE THREAD

**Issue by mohsin485** [SequentMicrosystems/4relay-rpi#3]
i am using raspberry pi 2 with 4-relay card and using 4-relay-rpi library and i have also enabled the i2c communication but when i enter the command 4relay -list it shows 0 board detected and when i try to test by using command 4relay 0 test it gives relay8 id 0 not detected .

**Comment by alexburcea2877** [comment]
Hi,
Your card is not communicate with raspberry, try to replug the 40pin
connector or tite the standoffs.
You also detect a typo in the python library, thank you, I will correct it
soon.

Let me know if you solve the problem.
Regards,
Alex.

**Comment by mohsin485** [comment]
My issue has been resolved by changing the raspberry pi , On that time i was using Raspberry pi 2 and now i am using raspberry pi 3 , Can you please tell me how to code in python editor as i am doing this in shell script . Thanks in advance .

**Comment by alexburcea2877** [comment]
Hi,
Follow the instructions to install the python library :
https://github.com/SequentMicrosystems/4relay-rpi/blob/master/python/README.md
Here you find a list of exported functions with descriptions.
If you use python3.x, you need to install library for python3 by changing
line:

~/4relay-rpi/python/4relay$ sudo python setup.py install

with :

~/4relay-rpi/python/4relay$ sudo python3 setup.py install


În vin., 24 iul. 2020 la 14:23, Mohsin733 <notifications@github.com> a
scris:

**Comment by mohsin485** [comment]
Thank you so much for helping out .
