### ISSUE TITLE
4relay card id not detected

### ISSUE THREAD

**Issue by bumpyessex** [SequentMicrosystems/4relay-rpi#6]
4relay -list
1 board detected
Id: 3 (should be id 0 based on the hardware setup)

4relay 3 read
4-RELAY card id 3 not detected

I'm very new at this and have the PWM Fan HAT also installed (if I remove the Fan HAT no boards are detected at all). Could you help me as I can't communicate with the 4relay board at all. I am running a raspberry pi 4.

Thanks

**Comment by bumpyessex** [comment]
After hours of research i finally found the answer.

In /boot/config.txt add:

#dtparam=i2c_arm=on
dtoverlay=i2c-gpio,i2c_gpio_sda=2,i2c_gpio_scl=3,i2c_gpio_delay_us=2,bus=1

No idea why this works but its fixed the issue.

**Comment by alexburcea2877** [comment]
Thank you for posting here the solution. 
Normally the "raspi-config" deal with the I2C settings, I never edit the boot/config.txt 
What Raspberry Pi and what os you have, we might learn something from your experience.

Alex.

**Comment by bumpyessex** [comment]
Of course, not a problem.
I am using a Raspberry Pi 4 (4GB) with Raspbian version 10 (buster).

I did enable I2C through "raspi-config" but it didn't seem to help, which is why I looked all over and found the above solution (sorry I can remember the source).

**Comment by alexburcea2877** [comment]
Thank you.
